name: 代码覆盖率
on:
  watch:
    types: started
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go v1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into current branch
        uses: actions/checkout@v2

      - name: Code Cover
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
