name: BUILD Linux
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go v1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Set Go Path && Build tool
        run: |
          go env -w GO111MODULE=on
          go env -w GOPATH=$GOROOT
          go get -u github.com/gobuffalo/packr/packr

      - name: Check out code into current branch
        uses: actions/checkout@v2

      - name: Make all
        run: |
          make all

      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          body: Release for new version
          files: |
            ./release/*
            ./conf/config.yaml.example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}