name: BUILD Linux
on:
  push:
    tags:
      - 'v*.**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set Go Path && Build tool
        run: |
          go env -w GO111MODULE=on
          go install github.com/gobuffalo/packr/packr@latest

      - name: Check out code into current branch
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: web/omsUI/yarn.lock

      - name: Node build
        run: |
          cd web/omsUI
          npm install yarn
          node_modules/.bin/yarn
          npm run build

      - name: Make all
        run: |
          make all

      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          body: Release for new version
          files: |
            ./release/*
            ./configs/config.yaml.example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker login
        run: |
          docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ssbeatty/oms/oms
          tag_with_ref: true