name: BUILD Linux
on:
  push:
    tags:
      - 'v*.**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: |
          # https://github.com/actions/setup-go/issues/107
          cp -f `which go` /usr/bin/go

      - name: Set Go Path && Build tool
        run: |
          go env -w GO111MODULE=on
          go install github.com/gobuffalo/packr/packr@latest

      - name: Check out code into current branch
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Node build
        run: |
          cd web/omsUI
          npm install
          npm run build

      - name: Make all
        run: |
          make all
